spring.application.name=Tienda Web Express
server.port=8080

# Forzamos a Spring a buscar el perfil local si estás en tu compu,
# pero si estás en la nube, Railway/Render lo ignorará e inyectará sus variables.
spring.profiles.include=local

# =============================================================
# CONFIGURACIÓN COMPARTIDA PARA LA NUBE (POSTGRESQL)
# =============================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.thymeleaf.cache=false